/**
 * Blog data layer. Metadata comes from posts.json (generated by _migration/transform.mjs);
 * post bodies are the exact-HTML files in astro-src/content/blog/, loaded raw at build time.
 */
import postsMeta from './posts.json';
import authorsData from './authors.json';
import categoriesData from './categories.json';
import pagesData from './pages.json';
import siteData from './site.json';

export interface TocItem { id: string; text: string; level: number }
export interface FaqItem { q: string; a: string }
export interface BlogPost {
  id: number; slug: string; title: string; date: string; modified: string;
  author_login: string; author_id: number; author_name: string;
  categories: string[]; category_names: string[]; tags: string[];
  description: string; description_source: string;
  featured_image: string; featured_image_w: number; featured_image_h: number;
  toc: TocItem[]; faq: FaqItem[]; body: string;
}
export interface Author {
  id: number; login: string; display_name: string; bio: string;
  avatar_url: string; linkedin: string; x_url: string; github: string; post_count: number;
}
export interface Category { term_id: number; name: string; slug: string; description: string; count: number }

// Raw HTML bodies (exact-HTML preservation)
const bodyModules = import.meta.glob('../../blog-content/*.html', { query: '?raw', import: 'default', eager: true }) as Record<string, string>;
const bodyBySlug: Record<string, string> = {};
for (const [p, html] of Object.entries(bodyModules)) {
  const m = p.match(/\/([^/]+)\.html$/);
  if (m) bodyBySlug[m[1]] = html as unknown as string;
}

export const posts: BlogPost[] = (postsMeta as Omit<BlogPost, 'body'>[]).map((p) => ({
  ...p,
  body: bodyBySlug[p.slug] || '',
}));

export interface BlogPage { id: number; slug: string; title: string; date: string; modified: string; meta_description: string; template: string }

export const authors = authorsData as Author[];
export const categories = categoriesData as Category[];
export const pages = pagesData as BlogPage[];
export const pageBySlug = (slug: string) => pages.find((p) => p.slug === slug);
export const site = siteData as { name: string; description: string; home_url: string };

// Fallback OG image (WP attachment 682), self-hosted.
export const OG_FALLBACK = '/blog/media/2026/02/dc-blog-og.png';

// Card/featured excerpt — mirrors get_the_excerpt() + wp_trim_words(). Strips the body
// to text and returns the first `words` words with an ellipsis when truncated.
export function excerptText(post: BlogPost, words = 20): string {
  const text = post.body
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&[^;]+;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const parts = text.split(' ');
  return parts.length > words ? parts.slice(0, words).join(' ') + '…' : text;
}

export const postBySlug = (slug: string) => posts.find((p) => p.slug === slug);
export const authorById = (id: number) => authors.find((a) => a.id === id);
export const authorByLogin = (login: string) => authors.find((a) => a.login === login);
export const categoryBySlug = (slug: string) => categories.find((c) => c.slug === slug);
export const postsByCategory = (slug: string) => posts.filter((p) => p.categories.includes(slug));
export const postsByAuthor = (login: string) => posts.filter((p) => p.author_login === login);
