name: PR Preview with Surge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for preview
        run: |
          # Build with relative paths for surge
          npx vite build --base="./"
        
      - name: Install Surge
        run: npm install -g surge
        
      - name: Deploy to Surge
        run: |
          # Deploy to surge with PR-specific domain
          surge ./docs desktop-commander-pr-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'PR Preview Deployed'
          
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🚀 PR Preview Deployed!
            
            **Preview URL:** https://desktop-commander-pr-${{ github.event.pull_request.number }}.surge.sh/
            
            ✅ This preview is updated automatically when you push commits to this PR.
            
            <details>
            <summary>Deployment Details</summary>
            
            - **Commit:** ${{ github.sha }}
            - **Branch:** ${{ github.head_ref }}
            - **Workflow:** [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - **Platform:** Surge.sh
            
            </details>
          edit-mode: replace
